# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/slate@v0.2.0
remote_theme: pages-themes/minima@v2.5.2
plugins:
- jekyll-remote-theme
title: Crankcoder's homepage
description: Bookmark this to keep an eye on my project updates!